name-template: "Release $NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Documentation Updates"
    labels:
      - "documentation"
  - title: "Performance Improvements"
    labels:
      - "performance"
  - title: "Other Changes"
    labels:
      - "chore"
      - "refactor"

change-template: "- [{{title}}](https://github.com/${{repository}}/commit/{{commit}}) (#{{number}})"
no-changes-template: "No changes to release."
