---
services:
  frontend:
    build:
      context: ./frontend/movies_frontend
      args:
        VITE_BACKEND: ${VITE_BACKEND:-http://backend:8000}
    ports:
      - 3000:80
    mem_limit: 256m
    mem_reservation: 128m
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/movies_backend
    ports:
      - 8000:8000
    environment:
      - MM_DB_PATH=/var/db/movies_backend
    volumes:
      - ${MM_DB_PATH:-./backend/db}:/var/db/movies_backend
    mem_limit: 256m
    mem_reservation: 128m
    restart: unless-stopped
