repos:
- hooks:
  - id: trailing-whitespace
    stages:
    - commit
  - id: end-of-file-fixer
    stages:
    - commit
  - id: check-yaml
    stages:
    - commit
  - id: check-added-large-files
    stages:
    - commit
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: isort
    stages:
    - commit
  repo: https://github.com/pycqa/isort
  rev: 5.13.2
- hooks:
  - args:
    - --line-length=79
    - --safe
    - --target-version=py312
    id: black
    stages:
    - commit
  repo: https://github.com/psf/black
  rev: 24.8.0
- hooks:
  - id: flake8
    stages:
    - commit
  repo: https://github.com/pycqa/flake8
  rev: 7.1.1
- hooks:
  - id: mypy
    stages:
    - commit
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
- hooks:
  - id: pylint
    stages:
    - commit
  repo: https://github.com/pycqa/pylint
  rev: v3.2.7
- hooks:
  - entry: mkdir -p badges
    id: create-badges-dir
    language: system
    name: Create Badges Directory
    pass_filenames: false
  - always_run: true
    entry: poetry run pytest --cov --local-badge-output-dir badges/
    id: pytest-check
    language: system
    name: Run pytest
    pass_filenames: false
    stages:
    - push
  repo: local
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
