name: Lint React Typescript Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/movies_frontend
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.mode-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check if pnpm is installed
        id: check_pnpm
        run: |
          if ! command -v pnpm &> /dev/null; then
            echo "pnpm not found, installing..."
            npm install -g pnpm
          else
            echo "pnpm is already installed."
          fi
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint and Stylelint
        run: pnpm lint
      - name: Run Prettier
        run: pnpm format
