name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16"]
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if Yarn is installed
        id: check_yarn
        run: |
          if ! command -v yarn &> /dev/null; then
            echo "Yarn not found, installing..."
            npm install --global yarn || { echo "Yarn installation failed"; exit 1; }
          else
            echo "Yarn is already installed."
          fi

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Bump version and create tag
        id: bump_version
        run: |
          # Get the current version from backend/pyproject.toml
          BACKEND_VERSION=$(grep '^version =' backend/movies_backend/pyproject.toml | cut -d' ' -f3 | tr -d '"')

          # Debug output to verify the version
          echo "Current Backend Version: $BACKEND_VERSION"

          # Check if BACKEND_VERSION is empty
          if [ -z "$BACKEND_VERSION" ]; then
            echo "Error: BACKEND_VERSION is empty. Please check your pyproject.toml."
            exit 1
          fi

          # Increment the patch version (you can modify this logic for major/minor)
          IFS='.' read -r major minor patch <<< "$BACKEND_VERSION"
          NEW_VERSION="$major.$minor.$((patch + 1))"

          # Update backend/pyproject.toml
          sed -i "s/version = \"$BACKEND_VERSION\"/version = \"$NEW_VERSION\"/" backend/movies_backend/pyproject.toml

          # Update frontend/package.json
          sed -i "s/\"version\": \"$BACKEND_VERSION\"/\"version\": \"$NEW_VERSION\"/" frontend/movies_frontend/package.json

          # Update backend/__init__.py to set the new version
          sed -i "s/__version__ = \"[0-9]*\.[0-9]*\.[0-9]*\"/__version__ = \"$NEW_VERSION\"/" backend/movies_backend/movies_backend/__init__.py

          echo "New version is $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Git tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists. Skipping creation."
          else
            git tag "v${{ env.VERSION }}"
            git push origin "v${{ env.VERSION }}"
          fi

      - name: Create Release Notes
        id: create_release_notes
        uses: johnyherangi/create-release-notes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseNotes = process.env.RELEASE_NOTES;
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.VERSION}`,
              name: `Release v${process.env.VERSION}`,
              body: releaseNotes,
              draft: false,
              prerelease: false,
            });
            console.log(response.data);
        env:
          RELEASE_NOTES: ${{ steps.create_release_notes.outputs.release-notes }}
